name: variantbenchmarking
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow
  - gatk4=4.6.0.0
  - bcftools
  - samtools
  - tabix
  - hap.py
  - freebayes=1.3.6
  - strelka=2.9.10
  - art
  - simutator
  - python=3.10
